#!/bin/sh
# This script deploys the app and initializes the gitlab repo for automated continuous integration and deployment

if [ -f easyinnit.config ]
then
  echo config file found, sourcing...
  source easyinnit.config

else

  echo no config file found, prompting for variables

  echo enter gitlab username
  read username

  echo enter gitlab domain \(\"gitlab.com\" or \"git.mydomain.com\"\)
  read gitlab_domain

  echo enter gitlab personal token
  read token

  echo enter app name \(if a django app, this must match your django project name\)
  echo this will become the name of the gitlab repository and the dokku app\)
  read appname

  echo new server\'s ip address
  read ip

  echo enter domain for new app \(\"mynewapp.mydomain.com\"\)
  read domain

  echo enter email for letsencrypt.org
  read email

  echo enter app type \(\"flask\" or \"django\"\)
  read app_type


  echo "username=$username
gitlab_domain=$gitlab_domain
token=$token
appname=$appname
ip=$ip
domain=$domain
email=$email
app_type=$app_type" >> easyinnit.config


fi

echo "function gi() { curl -sL https://www.toptal.com/developers/gitignore/api/\$@ ;}" >> \
~/.bashrc && source ~/.bashrc

gi python,pycharm >> .gitignore

pip install gunicorn

if [ "$app_type" = "flask" ]
then
  echo "web: gunicorn app:app" > Procfile
else [ "$app_type" = "django" ]
  echo "web: gunicorn $appname.wsgi" > Procfile
  echo "python-3.8.10" > runtime.txt
  echo "f = open(\"$appname/settings.py\")
with open(\"$appname/settings.py\", \"a\") as f:
    f.write(\"\nPROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))\nSTATIC_ROOT = \"
            \"os.path.join(PROJECT_ROOT, 'static')\nALLOWED_HOSTS = ['$ip','$domain']\n\")

with open(\"$appname/settings.py\") as f:
    lines = f.readlines()

with open(\"$appname/settings.py\", \"w\") as f:
    lines.insert(0, \"import os\n\")
    f.write(\"\".join(lines))" > easyinnit_django_settings.py
  python3 easyinnit_django_settings.py
  python3 manage.py collectstatic
  python3 manage.py makemigrations
  python3 manage.py migrate
fi




echo "image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  only:
    - main
  variables:
    GIT_REMOTE_URL: ssh://dokku@$ip:22/$appname
  script: dokku-deploy
  after_script: [dokku-unlock]" > .gitlab-ci.yml

pip freeze > requirements.txt

# initialize git appname
# shellcheck disable=SC2164
cd existing_folder
git init --initial-branch=main
git push --set-upstream git@git.synctivate.com:/$username/$appname.git
git remote add origin git@git.synctivate.com:$username/$appname.git
git add .
git commit -m "Initial commit"
git push -u origin main

#https://stackoverflow.com/questions/1955505/parsing-json-with-unix-tools
runner_token=$(curl --header "PRIVATE-TOKEN: $token" "https://$gitlab_domain/api/v4/projects/$username%2F$appname" | \
python3 -c "import sys, json; print(json.load(sys.stdin)['runners_token'])")


# shellcheck disable=SC1078
# shellcheck disable=SC2217
echo "#! /bin/sh
# shellcheck disable=SC1079
ssh-keygen -t rsa -N \"\" -f /root/.ssh/id_rsa

ssh_key=\`cat /root/.ssh/id_rsa\`
echo ssh key: \$ssh_key

curl --request POST --header \"PRIVATE-TOKEN: $token\" \
    \"https://$gitlab_domain/api/v4/projects/$username%2F$appname/variables\" \
    --form \"key=SSH_PRIVATE_KEY\" --form \"value=\$ssh_key\"

wget https://raw.githubusercontent.com/dokku/dokku/v0.28.4/bootstrap.sh
sudo DOKKU_TAG=v0.28.4 bash bootstrap.sh
cat ~/.ssh/authorized_keys | dokku ssh-keys:add admin
dokku apps:create $appname
dokku domains:clear-global
dokku domains:set $appname $domain
dokku proxy:ports-set $appname http:80:5000

# Download the binary for your system
sudo curl -L --output /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64

# Give it permission to execute
sudo chmod +x /usr/local/bin/gitlab-runner

# Create a GitLab Runner user
sudo useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash

# Install and run as a service
sudo gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
sudo gitlab-runner start

sudo gitlab-runner register \
  --non-interactive \
  --url \"https://$gitlab_domain/\" \
  --registration-token \"$runner_token\" \
  --executor \"docker\" \
  --docker-image alpine:latest \
  --description \"docker-runner\" \
  --maintenance-note \"Free-form maintainer notes about this runner\" \
  --tag-list \"project7, dokku\" \
  --run-untagged=\"true\" \
  --locked=\"false\" \
  --access-level=\"not_protected\"

sudo dokku plugin:install https://github.com/dokku/dokku-letsencrypt.git
dokku config:set --no-restart $appname DOKKU_LETSENCRYPT_EMAIL=$email
dokku letsencrypt:enable $appname
dokku letsencrypt:cron-job --add

" > server-script.sh

ssh root@$ip "bash -s" < server-script.sh
